name: chat_pet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui utils
  flutter_screenutil: ^5.9.3
  awesome_extensions:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  logger: ^2.6.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Caros
      fonts:
        - asset: assets/fonts/Caros.otf
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.otf
  uses-material-design: true
